### ISSUE TITLE
Not accepting 60mbps+ upload speed

### ISSUE THREAD

**Issue by juliustip** [AliMickey/starlink-data-tracker#7]
Tried adding a speedtest result https://www.speedtest.net/my-result/d/488388231
But it's not accepting upload speed above 60mbps.

Live speedtest video https://youtu.be/t_itjNsXHFg?t=14

**Comment by AliMickey** [comment]
Hey, apologies for not replying earlier. Didn't get a notification.

Greatly appreciate your video submission, but would it be possible if you could reproduce the 60mbps> upload with a separate testing site or file uploading.

Speedtest.net sometimes reports inaccurate results.

**Comment by AliMickey** [comment]
Feel free to open the issue if you need.
