### ISSUE TITLE
Zabbix Template for Starlink Dishy

### ISSUE THREAD

**Issue by smejdil** [AliMickey/starlink-data-tracker#8]
Hi
I am using your project to monitor Starlink Dish using Prometeus exporter. I'm uploading templates for Zabbix 6.0

https://github.com/smejdil/zabbix-ansible/blob/main/templates/Template_Starlink_dish.xml
https://github.com/smejdil/zabbix-ansible/blob/main/templates/Template_Starlink_dish.yam
https://github.com/smejdil/zabbix-ansible/blob/main/templates/Template_Starlink_dish.jsonl

**Comment by AliMickey** [comment]
Very nice! Thanks for sharing.
